server:
  port: 9000
spring:
  application:
    name: web-user
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka
fdfs:
  pool:
    jmx-enabled: false
  thumb-image:
    width: 80
    height: 80
  tracker-list: 10.36.138.254.22122