server:
  port: 10086
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - uri: lb://WEB-USER
          predicates:
            - Path=/user/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka